version: "3"
services:
    db:
        image:  ${DB_IMAGE_NAME}
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "${DB_CONTAINER_PORT}:${DB_CONTAINER_PORT}"
        command:
            -p ${DB_CONTAINER_PORT}
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    api:
        build: 
            .
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            - db
        environment:
            DB_HOST: db

volumes:
    db_data: