version: "3"
services:
  db:
    image:  ${DB_IMAGE_NAME}
    restart: always
    ports:
      - "${DB_CONTAINER_PORT}:${DB_CONTAINER_INTERNAL_PORT}"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}